/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ControlAcceso;

/**
 *
 * @author Lore
 */
public class CambioContraseña extends javax.swing.JFrame {

    /**
     * Creates new form CambioContraseña
     */
    public CambioContraseña() {
        initComponents();
        initComponents();
        setLocationRelativeTo(null);
     setResizable(false);
    setTitle("Cambio de contraseña");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ContraAnte = new javax.swing.JLabel();
        NuevaContra = new javax.swing.JLabel();
        ConfirmaContra = new javax.swing.JLabel();
        Rut = new javax.swing.JLabel();
        TextContraAnte = new javax.swing.JTextField();
        TextNuevaContra = new javax.swing.JTextField();
        TextConfirContra = new javax.swing.JTextField();
        TextRut = new javax.swing.JTextField();
        BotonAcepCambCon = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ContraAnte.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        ContraAnte.setText("Contraseña Actual");

        NuevaContra.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        NuevaContra.setText("Nueva Contraseña");

        ConfirmaContra.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        ConfirmaContra.setText("Confirmar Nueva Contraseña");

        Rut.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        Rut.setText("Rut");

        TextContraAnte.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        TextNuevaContra.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        TextNuevaContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextNuevaContraActionPerformed(evt);
            }
        });
        TextNuevaContra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextNuevaContraKeyTyped(evt);
            }
        });

        TextConfirContra.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        TextRut.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        BotonAcepCambCon.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        BotonAcepCambCon.setText("Aceptar");
        BotonAcepCambCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAcepCambConActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jButton1.setText("Atrás");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lore\\Documents\\NetBeansProjects\\ ControlAcceso\\nbproject\\logo utem.jpg")); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ContraAnte)
                                    .addComponent(NuevaContra))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextConfirContra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextRut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ConfirmaContra)
                                    .addComponent(Rut))
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TextNuevaContra, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(TextContraAnte))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 122, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(70, 70, 70)
                        .addComponent(BotonAcepCambCon)
                        .addGap(136, 136, 136))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(215, 215, 215))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Rut)
                            .addComponent(TextNuevaContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ContraAnte)
                            .addComponent(TextRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NuevaContra)
                            .addComponent(TextConfirContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ConfirmaContra)
                            .addComponent(TextContraAnte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonAcepCambCon)
                    .addComponent(jButton1))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonAcepCambConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAcepCambConActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonAcepCambConActionPerformed

    private void TextNuevaContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextNuevaContraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextNuevaContraActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      Opciones obj=new Opciones();
      obj.setVisible(true);
      dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TextNuevaContraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextNuevaContraKeyTyped
                char n =evt.getKeyChar();
        if(n<'0' || n>'9'){
            getToolkit().beep();
            evt.consume();}
    }//GEN-LAST:event_TextNuevaContraKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CambioContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CambioContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CambioContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CambioContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CambioContraseña().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAcepCambCon;
    private javax.swing.JLabel ConfirmaContra;
    private javax.swing.JLabel ContraAnte;
    private javax.swing.JLabel NuevaContra;
    private javax.swing.JLabel Rut;
    private javax.swing.JTextField TextConfirContra;
    private javax.swing.JTextField TextContraAnte;
    private javax.swing.JTextField TextNuevaContra;
    private javax.swing.JTextField TextRut;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
